export enum WebSocketActionTypes {
  WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT",
  WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT",
  WEBSOCKET_SEND_MESSAGE = "WEBSOCKET_SEND_MESSAGE",
  WEBSOCKET_RECEIVE_MESSAGE = "WEBSOCKET_RECEIVE_MESSAGE"
}